# Generated by Django 5.0.4 on 2025-09-10 13:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethodOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "method_type",
                    models.CharField(
                        choices=[("offline", "offline"), ("online", "online")],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("legacy_value", models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "ecommerce_payment_methods",
                "ordering": ["-created_at"],
            },
        ),
    ]
